### PR TITLE
feat(handler,website): remove unused commands

### PR DESCRIPTION
**Pull request by iCrawl**
Based on feedback talk with @almostSouji, we concluded that there should be three different applications handling separated logic.

Yuudachi - The moderation bot
Project X - The log aggregation for discord
Project Y - The organizational bot

### CODE REVIEW

**Comment by appellation** [comment]
Is the thought here to have a separate _bot_ for specific functionality or to have a separate _application_ for specific functionality? I would disagree with having a separate application, since there's still a lot of common ground such as sign-in, data storage, permissions, boilerplate, etc. that would be duplicated.

If the thought is to have a separate bot but keep everything in the same application, it should be relatively trivial to setup each gateway with a corresponding handler. It would just be a matter of using a distinct AMQP group for each bot-handler pairing. Rather than removing these commands, we would just move them to the appropriate handler directory.

**Comment by iCrawl** [comment]
Yes, separate bots.
I am not entirely sure how to structure it yet but Project Y (organizational) would be running completely on the new interactions discord put out.

This would mean you would not need an actual bot on the server but it all runs over webhooks.

For the log aggregator it would be a separate bot which as you said could definitely benefit from the gateway grouping here.

Generally speaking I was unsure how to incorporate that with the database level here more so than anything else. I could leverage different Postgres Schemas here. But I have no huge experience in those yet so it would take some time to look into, or a different database all together. 
Sole reason being because the moderation commands in the main bot are the primary focus. Keeping logs, tags, docs etc are optional and may not be needed from guild to guild.

**Comment by appellation** [comment]
Ah, that makes a lot of sense. Thank you for clarifying.

If we're looking for a more distinct separation between the data for these separate services, I can see that database schemas might be an appropriate approach here. I wouldn't have any issues with keeping everything in the same schema, though, since there is little chance that we will run into organizational difficulties at this scale. https://www.postgresql.org/docs/current/ddl-schemas.html

image

My main concern is that we maintain a cohesive ecosystem here so that, for example, a guild that sets its locale for one service is not required to do so for any other service.

**Comment by iCrawl** [comment]
> My main concern is that we maintain a cohesive ecosystem here so that, for example, a guild that sets its locale for one service is not required to do so for any other service.

I 100% agree with this here. The other services would be an "addon" and not necessarily work without the main "bot".
This is also why the main "public" schema (postgres default) would still contain the necessary parts like users, connections, guild_settings. None of those would go into their own. The separate schemas would rather be for tags, github aliases etc. So that those have a bigger breathing room and the database itself (main schema) doesn't feel as cluttered with all kinds of different information. Each schema would have its dedicated place.

I think this would also make it easier for me to have a proper overview of things and expand into multiple tables and can make tags / cases / documentation a bit more fleshed out. It would lead to having more tables with more information in their dedicated places instead of having a lot of `prefix_tablename` for each dedicated optional informational piece.

**Comment by iCrawl** [comment]
I will move forward with #850 then and pulling them out at a later date.

**Pull request closed without merging**
